/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class ACCESS4args : XdrAble
    {
    public uint32_t access;


    public ACCESS4args() {
    }

    public ACCESS4args(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        access.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        access = new uint32_t(xdr);
    }

    }
}
// End of ACCESS4args.cs
