/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class ACCESS4resok : XdrAble
    {
        public uint32_t supported;
        public uint32_t access;


        public ACCESS4resok()
        {
        }

        public ACCESS4resok(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            supported.xdrEncode(xdr);
            access.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            supported = new uint32_t(xdr);
            access = new uint32_t(xdr);
        }
    }
}
// End of ACCESS4resok.cs
