/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class attr_notice4 : XdrAble
    {

        public nfstime4 value;

        public attr_notice4()
        {
        }

        public attr_notice4(nfstime4 value)
        {
            this.value = value;
        }

        public attr_notice4(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            value.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            value = new nfstime4(xdr);
        }

    }
}
// End of attr_notice4.cs
