/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class BACKCHANNEL_CTL4args : XdrAble
    {
        public int bca_cb_program;
        public callback_sec_parms4[] bca_sec_parms;

        public BACKCHANNEL_CTL4args()
        {
        }

        public BACKCHANNEL_CTL4args(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            { int _size = bca_sec_parms.Length; xdr.xdrEncodeInt(_size); for (int _idx = 0; _idx < _size; ++_idx) { bca_sec_parms[_idx].xdrEncode(xdr); } }
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            { int _size = xdr.xdrDecodeInt(); bca_sec_parms = new callback_sec_parms4[_size]; for (int _idx = 0; _idx < _size; ++_idx) { bca_sec_parms[_idx] = new callback_sec_parms4(xdr); } }
        }

    }
}
// End of BACKCHANNEL_CTL4args.cs
