/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class BIND_CONN_TO_SESSION4res : XdrAble
    {
        public int bctsr_status;
        public BIND_CONN_TO_SESSION4resok bctsr_resok4;

        public BIND_CONN_TO_SESSION4res()
        {
        }

        public BIND_CONN_TO_SESSION4res(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            xdr.xdrEncodeInt(bctsr_status);
            switch (bctsr_status)
            {
                case nfsstat4.NFS4_OK:
                    bctsr_resok4.xdrEncode(xdr);
                    break;
                default:
                    break;
            }
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            bctsr_status = xdr.xdrDecodeInt();
            switch (bctsr_status)
            {
                case nfsstat4.NFS4_OK:
                    bctsr_resok4 = new BIND_CONN_TO_SESSION4resok(xdr);
                    break;
                default:
                    break;
            }
        }

    }
}
// End of BIND_CONN_TO_SESSION4res.cs
