/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class BIND_CONN_TO_SESSION4args : XdrAble
    {
        public sessionid4 bctsa_sessid;
        public int bctsa_dir;
        public bool bctsa_use_conn_in_rdma_mode;

        public BIND_CONN_TO_SESSION4args()
        {
        }

        public BIND_CONN_TO_SESSION4args(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            xdr.xdrEncodeInt(bctsa_dir);
            xdr.xdrEncodeBoolean(bctsa_use_conn_in_rdma_mode);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            bctsa_dir = xdr.xdrDecodeInt();
            bctsa_use_conn_in_rdma_mode = xdr.xdrDecodeBoolean();
        }

    }
}
// End of BIND_CONN_TO_SESSION4args.cs
