/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class bitmap4 : XdrAble
    {

    public uint32_t [] value;


    public bitmap4() {
    }

    public bitmap4(uint32_t [] value) {
        this.value = value;
    }

    public bitmap4(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        { int size = value.Length; xdr.xdrEncodeInt(size); for ( int idx = 0; idx < size; ++idx ) { value[idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        { int size = xdr.xdrDecodeInt(); value = new uint32_t[size]; for ( int idx = 0; idx < size; ++idx ) { value[idx] = new uint32_t(xdr); } }
    }

    }
}
// End of bitmap4.cs
