/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class cb_client4 : XdrAble
    {
        public int cb_program;
        public netaddr4 cb_location;

        public cb_client4()
        {
        }

        public cb_client4(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            cb_location.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            cb_location = new netaddr4(xdr);
        }

    }
}
// End of cb_client4.cs
