/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class change_info4 : XdrAble
    {
    public bool atomic;
    public changeid4 before;
    public changeid4 after;


    public change_info4() {
    }

    public change_info4(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        xdr.xdrEncodeBoolean(atomic);
        before.xdrEncode(xdr);
        after.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
   {
        atomic = xdr.xdrDecodeBoolean();
        before = new changeid4(xdr);
        after = new changeid4(xdr);
    }

    }
}
// End of change_info4.cs
