/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class channel_dir_from_server4
    {

        public const int CDFS4_FORE = 0x1;
        public const int CDFS4_BACK = 0x2;
        public const int CDFS4_BOTH = 0x3;

    }
}
// End of channel_dir_from_server4.cs
