/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class change_policy4 : XdrAble
    {
        public int cp_major;
        public int cp_minor;

        public change_policy4()
        {
        }

        public change_policy4(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            xdr.xdrEncodeInt(cp_minor);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            cp_minor = xdr.xdrDecodeInt();
        }

    }
}
// End of change_policy4.cs
