/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class COMPOUND4res : XdrAble {
    public int status;
    public utf8str_cs tag;
    public nfs_resop4 [] resarray;

    public COMPOUND4res() {
    }

    public COMPOUND4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(status);
        tag.xdrEncode(xdr);
        { int _size = resarray.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { resarray[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        status = xdr.xdrDecodeInt();
        tag = new utf8str_cs(xdr);
        { int _size = xdr.xdrDecodeInt(); resarray = new nfs_resop4[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { resarray[_idx] = new nfs_resop4(xdr); } }
    }

}
} // End of COMPOUND4res.cs
