/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class COMPOUND4args : XdrAble {
    public utf8str_cs tag;
    public uint32_t minorversion;
    public nfs_argop4 [] argarray;


    public COMPOUND4args() {
    }

    public COMPOUND4args(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
      {
        tag.xdrEncode(xdr);
        minorversion.xdrEncode(xdr);
        { int size = argarray.Length; xdr.xdrEncodeInt(size); for ( int idx = 0; idx < size; ++idx ) { argarray[idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
      {
        tag = new utf8str_cs(xdr);
        minorversion = new uint32_t(xdr);
        { int size = xdr.xdrDecodeInt(); argarray = new nfs_argop4[size]; for ( int idx = 0; idx < size; ++idx ) { argarray[idx] = new nfs_argop4(xdr); } }
    }

}
} // End of COMPOUND4args.cs
