/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class entry4 : XdrAble {
    public nfs_cookie4 cookie;
    public component4 name;
    public fattr4 attrs;
    public entry4 nextentry;

    public entry4() {
    }

    public entry4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        entry4 _this = this;
        do {
            _this.cookie.xdrEncode(xdr);
            _this.name.xdrEncode(xdr);
            _this.attrs.xdrEncode(xdr);
            _this = _this.nextentry;
            xdr.xdrEncodeBoolean(_this != null);
        } while ( _this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        entry4 _this = this;
        entry4 _next;
        do {
            _this.cookie = new nfs_cookie4(xdr);
            _this.name = new component4(xdr);
            _this.attrs = new fattr4(xdr);
            _next = xdr.xdrDecodeBoolean() ? new entry4() : null;
            _this.nextentry = _next;
            _this = _next;
        } while ( _this != null );
    }

}
} // End of  entry4.cs
