/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class exist_lock_owner4 : XdrAble
    {
        public stateid4 lock_stateid;
        public seqid4 lock_seqid;

        public exist_lock_owner4()
        {
        }

        public exist_lock_owner4(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            lock_seqid.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            lock_seqid = new seqid4(xdr);
        }

    }
}
// End of exist_lock_owner4.cs
