/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class fattr4_retention_set : XdrAble {

    public retention_set4 value;

    public fattr4_retention_set() {
    }

    public fattr4_retention_set(retention_set4 value) {
        this.value = value;
    }

    public fattr4_retention_set(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        value.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        value = new retention_set4(xdr);
    }

}
} // End of  fattr4_retention_set.cs
