/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class fs4_status_type
    {

        public const int STATUS4_FIXED = 1;
        public const int STATUS4_UPDATED = 2;
        public const int STATUS4_VERSIONED = 3;
        public const int STATUS4_WRITABLE = 4;
        public const int STATUS4_REFERRAL = 5;

    }
}
// End of fs4_status_type.cs
