/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class fs_locations_info4 : XdrAble {
    public int fli_flags;
    public int fli_valid_for;
    public pathname4 fli_fs_root;
    public fs_locations_item4 [] fli_items;

    public fs_locations_info4() {
    }

    public fs_locations_info4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(fli_valid_for);
        fli_fs_root.xdrEncode(xdr);
        { int _size = fli_items.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { fli_items[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        fli_valid_for = xdr.xdrDecodeInt();
        fli_fs_root = new pathname4(xdr);
        { int _size = xdr.xdrDecodeInt(); fli_items = new fs_locations_item4[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { fli_items[_idx] = new fs_locations_item4(xdr); } }
    }

}
} // End of  fs_locations_info4.cs
