/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class gddrnf4_status
    {

        public const int GDD4_OK = 0;
        public const int GDD4_UNAVAIL = 1;

    }
}
// End of gddrnf4_status.cs
