/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class GET_DIR_DELEGATION4res : XdrAble {
    public int gddr_status;
    public GET_DIR_DELEGATION4res_non_fatal gddr_res_non_fatal4;

    public GET_DIR_DELEGATION4res() {
    }

    public GET_DIR_DELEGATION4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(gddr_status);
        switch ( gddr_status ) {
        case nfsstat4.NFS4_OK:
            gddr_res_non_fatal4.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        gddr_status = xdr.xdrDecodeInt();
        switch ( gddr_status ) {
        case nfsstat4.NFS4_OK:
            gddr_res_non_fatal4 = new GET_DIR_DELEGATION4res_non_fatal(xdr);
            break;
        default:
            break;
        }
    }

}
} // End of  GET_DIR_DELEGATION4res.cs
