/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class GET_DIR_DELEGATION4resok : XdrAble {
    public verifier4 gddr_cookieverf;
    public stateid4 gddr_stateid;
    public bitmap4 gddr_notification;
    public bitmap4 gddr_child_attributes;
    public bitmap4 gddr_dir_attributes;

    public GET_DIR_DELEGATION4resok() {
    }

    public GET_DIR_DELEGATION4resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        gddr_stateid.xdrEncode(xdr);
        gddr_notification.xdrEncode(xdr);
        gddr_child_attributes.xdrEncode(xdr);
        gddr_dir_attributes.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        gddr_stateid = new stateid4(xdr);
        gddr_notification = new bitmap4(xdr);
        gddr_child_attributes = new bitmap4(xdr);
        gddr_dir_attributes = new bitmap4(xdr);
    }

}
} // End of  GET_DIR_DELEGATION4resok.cs
