/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class GETDEVICELIST4res : XdrAble {
    public int gdlr_status;
    public GETDEVICELIST4resok gdlr_resok4;

    public GETDEVICELIST4res() {
    }

    public GETDEVICELIST4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(gdlr_status);
        switch ( gdlr_status ) {
        case nfsstat4.NFS4_OK:
            gdlr_resok4.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        gdlr_status = xdr.xdrDecodeInt();
        switch ( gdlr_status ) {
        case nfsstat4.NFS4_OK:
            gdlr_resok4 = new GETDEVICELIST4resok(xdr);
            break;
        default:
            break;
        }
    }

}
} // End of  GETDEVICELIST4res.cs
