/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class GETDEVICEINFO4res : XdrAble {
    public int gdir_status;
    public GETDEVICEINFO4resok gdir_resok4;
    public count4 gdir_mincount;

    public GETDEVICEINFO4res() {
    }

    public GETDEVICEINFO4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(gdir_status);
        switch ( gdir_status ) {
        case nfsstat4.NFS4_OK:
            gdir_resok4.xdrEncode(xdr);
            break;
        case nfsstat4.NFS4ERR_TOOSMALL:
            gdir_mincount.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        gdir_status = xdr.xdrDecodeInt();
        switch ( gdir_status ) {
        case nfsstat4.NFS4_OK:
            gdir_resok4 = new GETDEVICEINFO4resok(xdr);
            break;
        case nfsstat4.NFS4ERR_TOOSMALL:
            gdir_mincount = new count4(xdr);
            break;
        default:
            break;
        }
    }

}
} // End of  GETDEVICEINFO4res.cs
