/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class GETDEVICEINFO4resok : XdrAble {
    public device_addr4 gdir_device_addr;
    public bitmap4 gdir_notification;

    public GETDEVICEINFO4resok() {
    }

    public GETDEVICEINFO4resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        gdir_notification.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        gdir_notification = new bitmap4(xdr);
    }

}
} // End of  GETDEVICEINFO4resok.cs
