/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class GETDEVICEINFO4args : XdrAble {
    public deviceid4 gdia_device_id;
    public int gdia_layout_type;
    public count4 gdia_maxcount;
    public bitmap4 gdia_notify_types;

    public GETDEVICEINFO4args() {
    }

    public GETDEVICEINFO4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(gdia_layout_type);
        gdia_maxcount.xdrEncode(xdr);
        gdia_notify_types.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        gdia_layout_type = xdr.xdrDecodeInt();
        gdia_maxcount = new count4(xdr);
        gdia_notify_types = new bitmap4(xdr);
    }

}
} // End of  GETDEVICEINFO4args.cs
