/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class layoutiomode4
    {

        public const int LAYOUTIOMODE4_READ = 1;
        public const int LAYOUTIOMODE4_RW = 2;
        public const int LAYOUTIOMODE4_ANY = 3;

    }
}
 // End of layoutiomode4.cs
