/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class layoutupdate4 : XdrAble {
    public int lou_type;
    public byte [] lou_body;

    public layoutupdate4() {
    }

    public layoutupdate4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeDynamicOpaque(lou_body);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        lou_body = xdr.xdrDecodeDynamicOpaque();
    }

}
} // End of layoutupdate4.cs
