/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class LAYOUTCOMMIT4args : XdrAble {
    public offset4 loca_offset;
    public length4 loca_length;
    public bool loca_reclaim;
    public stateid4 loca_stateid;
    public newoffset4 loca_last_write_offset;
    public newtime4 loca_time_modify;
    public layoutupdate4 loca_layoutupdate;

    public LAYOUTCOMMIT4args() {
    }

    public LAYOUTCOMMIT4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        loca_length.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(loca_reclaim);
        loca_stateid.xdrEncode(xdr);
        loca_last_write_offset.xdrEncode(xdr);
        loca_time_modify.xdrEncode(xdr);
        loca_layoutupdate.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        loca_length = new length4(xdr);
        loca_reclaim = xdr.xdrDecodeBoolean();
        loca_stateid = new stateid4(xdr);
        loca_last_write_offset = new newoffset4(xdr);
        loca_time_modify = new newtime4(xdr);
        loca_layoutupdate = new layoutupdate4(xdr);
    }

}
} // End of LAYOUTCOMMIT4args.cs
