/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class LAYOUTRETURN4args : XdrAble {
    public bool lora_reclaim;
    public int lora_layout_type;
    public int lora_iomode;
    public layoutreturn4 lora_layoutreturn;

    public LAYOUTRETURN4args() {
    }

    public LAYOUTRETURN4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(lora_layout_type);
        xdr.xdrEncodeInt(lora_iomode);
        lora_layoutreturn.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        lora_layout_type = xdr.xdrDecodeInt();
        lora_iomode = xdr.xdrDecodeInt();
        lora_layoutreturn = new layoutreturn4(xdr);
    }

}
} // End of LAYOUTRETURN4args.cs
