/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
/**
 * Enumeration (collection of constants).
 */
public class layouttype4 {

    public const int LAYOUT4_NFSV4_1_FILES = 0x1;
    public const int LAYOUT4_OSD2_OBJECTS = 0x2;
    public const int LAYOUT4_BLOCK_VOLUME = 0x3;

}
} // End of layouttype4.cs
