/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class layouthint4 : XdrAble {
    public int loh_type;
    public byte [] loh_body;

    public layouthint4() {
    }

    public layouthint4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeDynamicOpaque(loh_body);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        loh_body = xdr.xdrDecodeDynamicOpaque();
    }

}
} // End of layouthint4.cs
