/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class layoutreturn_type4
    {

        public const int LAYOUTRETURN4_FILE = NFSv4Protocol.LAYOUT4_RET_REC_FILE;
        public const int LAYOUTRETURN4_FSID = NFSv4Protocol.LAYOUT4_RET_REC_FSID;
        public const int LAYOUTRETURN4_ALL = NFSv4Protocol.LAYOUT4_RET_REC_ALL;

    }
}
 // End of layoutreturn_type4.cs
