/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class LAYOUTGET4res : XdrAble {
    public int logr_status;
    public LAYOUTGET4resok logr_resok4;
    public bool logr_will_signal_layout_avail;

    public LAYOUTGET4res() {
    }

    public LAYOUTGET4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(logr_status);
        switch ( logr_status ) {
        case nfsstat4.NFS4_OK:
            logr_resok4.xdrEncode(xdr);
            break;
        case nfsstat4.NFS4ERR_LAYOUTTRYLATER:
            xdr.xdrEncodeBoolean(logr_will_signal_layout_avail);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        logr_status = xdr.xdrDecodeInt();
        switch ( logr_status ) {
        case nfsstat4.NFS4_OK:
            logr_resok4 = new LAYOUTGET4resok(xdr);
            break;
        case nfsstat4.NFS4ERR_LAYOUTTRYLATER:
            logr_will_signal_layout_avail = xdr.xdrDecodeBoolean();
            break;
        default:
            break;
        }
    }

}
} // End of LAYOUTGET4res.cs
