/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class LAYOUTGET4args : XdrAble {
    public bool loga_signal_layout_avail;
    public int loga_layout_type;
    public int loga_iomode;
    public offset4 loga_offset;
    public length4 loga_length;
    public length4 loga_minlength;
    public stateid4 loga_stateid;
    public count4 loga_maxcount;

    public LAYOUTGET4args() {
    }

    public LAYOUTGET4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(loga_layout_type);
        xdr.xdrEncodeInt(loga_iomode);
        loga_offset.xdrEncode(xdr);
        loga_length.xdrEncode(xdr);
        loga_minlength.xdrEncode(xdr);
        loga_stateid.xdrEncode(xdr);
        loga_maxcount.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        loga_layout_type = xdr.xdrDecodeInt();
        loga_iomode = xdr.xdrDecodeInt();
        loga_offset = new offset4(xdr);
        loga_length = new length4(xdr);
        loga_minlength = new length4(xdr);
        loga_stateid = new stateid4(xdr);
        loga_maxcount = new count4(xdr);
    }

}
} // End of LAYOUTGET4args.cs
