/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class LOCKT4args : XdrAble {
    public int locktype;
    public offset4 offset;
    public length4 length;
    public lock_owner4 owner;

    public LOCKT4args() {
    }

    public LOCKT4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        offset.xdrEncode(xdr);
        length.xdrEncode(xdr);
        owner.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        offset = new offset4(xdr);
        length = new length4(xdr);
        owner = new lock_owner4(xdr);
    }

}
} // End of LOCKT4args.cs
