/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class LOCKU4args : XdrAble {
    public int locktype;
    public seqid4 seqid;
    public stateid4 lock_stateid;
    public offset4 offset;
    public length4 length;

    public LOCKU4args() {
    }

    public LOCKU4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        seqid.xdrEncode(xdr);
        lock_stateid.xdrEncode(xdr);
        offset.xdrEncode(xdr);
        length.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        seqid = new seqid4(xdr);
        lock_stateid = new stateid4(xdr);
        offset = new offset4(xdr);
        length = new length4(xdr);
    }

}
} // End of LOCKU4args.cs
