/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class LOCKT4res : XdrAble {
    public int status;
    public LOCK4denied denied;

    public LOCKT4res() {
    }

    public LOCKT4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(status);
        switch ( status ) {
        case nfsstat4.NFS4ERR_DENIED:
            denied.xdrEncode(xdr);
            break;
        case nfsstat4.NFS4_OK:
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        status = xdr.xdrDecodeInt();
        switch ( status ) {
        case nfsstat4.NFS4ERR_DENIED:
            denied = new LOCK4denied(xdr);
            break;
        case nfsstat4.NFS4_OK:
            break;
        default:
            break;
        }
    }

}
} // End of LOCKT4res.cs
