/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class mode_masked4 : XdrAble {
    public mode4 mm_value_to_set;
    public mode4 mm_mask_bits;

    public mode_masked4() {
    }

    public mode_masked4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        mm_mask_bits.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        mm_mask_bits = new mode4(xdr);
    }

}
} // End of mode_masked4.cs
