/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class netaddr4 : XdrAble {
    public string na_r_netid;
    public string na_r_addr;

    public netaddr4() {
    }

    public netaddr4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeString(na_r_addr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        na_r_addr = xdr.xdrDecodeString();
    }

}
} // End of netaddr4.cs
