/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class newtime4 : XdrAble {
    public bool nt_timechanged;
    public nfstime4 nt_time;

    public newtime4() {
    }

    public newtime4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeBoolean(nt_timechanged);
        if ( nt_timechanged == true ) {
            nt_time.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        nt_timechanged = xdr.xdrDecodeBoolean();
        if ( nt_timechanged == true ) {
            nt_time = new nfstime4(xdr);
        }
    }

}
} // End of newtime4.cs
