/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class nfs_ftype4
    {

        public const int NF4REG = 1;
        public const int NF4DIR = 2;
        public const int NF4BLK = 3;
        public const int NF4CHR = 4;
        public const int NF4LNK = 5;
        public const int NF4SOCK = 6;
        public const int NF4FIFO = 7;
        public const int NF4ATTRDIR = 8;
        public const int NF4NAMEDATTR = 9;

    }
}
 // End of nfs_ftype4.cs
