/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class nfs_opnum4
    {

        public const int OP_ACCESS = 3;
        public const int OP_CLOSE = 4;
        public const int OP_COMMIT = 5;
        public const int OP_CREATE = 6;
        public const int OP_DELEGPURGE = 7;
        public const int OP_DELEGRETURN = 8;
        public const int OP_GETATTR = 9;
        public const int OP_GETFH = 10;
        public const int OP_LINK = 11;
        public const int OP_LOCK = 12;
        public const int OP_LOCKT = 13;
        public const int OP_LOCKU = 14;
        public const int OP_LOOKUP = 15;
        public const int OP_LOOKUPP = 16;
        public const int OP_NVERIFY = 17;
        public const int OP_OPEN = 18;
        public const int OP_OPENATTR = 19;
        public const int OP_OPEN_CONFIRM = 20;
        public const int OP_OPEN_DOWNGRADE = 21;
        public const int OP_PUTFH = 22;
        public const int OP_PUTPUBFH = 23;
        public const int OP_PUTROOTFH = 24;
        public const int OP_READ = 25;
        public const int OP_READDIR = 26;
        public const int OP_READLINK = 27;
        public const int OP_REMOVE = 28;
        public const int OP_RENAME = 29;
        public const int OP_RENEW = 30;
        public const int OP_RESTOREFH = 31;
        public const int OP_SAVEFH = 32;
        public const int OP_SECINFO = 33;
        public const int OP_SETATTR = 34;
        public const int OP_SETCLIENTID = 35;
        public const int OP_SETCLIENTID_CONFIRM = 36;
        public const int OP_VERIFY = 37;
        public const int OP_WRITE = 38;
        public const int OP_RELEASE_LOCKOWNER = 39;
        public const int OP_BACKCHANNEL_CTL = 40;
        public const int OP_BIND_CONN_TO_SESSION = 41;
        public const int OP_EXCHANGE_ID = 42;
        public const int OP_CREATE_SESSION = 43;
        public const int OP_DESTROY_SESSION = 44;
        public const int OP_FREE_STATEID = 45;
        public const int OP_GET_DIR_DELEGATION = 46;
        public const int OP_GETDEVICEINFO = 47;
        public const int OP_GETDEVICELIST = 48;
        public const int OP_LAYOUTCOMMIT = 49;
        public const int OP_LAYOUTGET = 50;
        public const int OP_LAYOUTRETURN = 51;
        public const int OP_SECINFO_NO_NAME = 52;
        public const int OP_SEQUENCE = 53;
        public const int OP_SET_SSV = 54;
        public const int OP_TEST_STATEID = 55;
        public const int OP_WANT_DELEGATION = 56;
        public const int OP_DESTROY_CLIENTID = 57;
        public const int OP_RECLAIM_COMPLETE = 58;
        public const int OP_ILLEGAL = 10044;

    }
}
 // End of nfs_opnum4.cs
