/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class nfs_impl_id4 : XdrAble {
    public utf8str_cis nii_domain;
    public utf8str_cs nii_name;
    public nfstime4 nii_date;

    public nfs_impl_id4() {
    }

    public nfs_impl_id4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        nii_domain.xdrEncode(xdr);
        nii_name.xdrEncode(xdr);
        nii_date.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        nii_domain = new utf8str_cis(xdr);
        nii_name = new utf8str_cs(xdr);
        nii_date = new nfstime4(xdr);
    }

}
} // End of nfs_impl_id4.cs
