/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class nfs_lock_type4
    {

        public const int READ_LT = 1;
        public const int WRITE_LT = 2;
        public const int READW_LT = 3;
        public const int WRITEW_LT = 4;

    }
}
 // End of nfs_lock_type4.cs
