/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;


    //TODO check similar NFSTimeValue
    public class nfstime4 : XdrAble
    {
        //is long
        public int64_t seconds;
        public uint32_t nseconds;

    public nfstime4() {
    }

    public nfstime4(XdrDecodingStream xdr)
            {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
          {
        seconds.xdrEncode(xdr);
        nseconds.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
          {
        seconds = new int64_t(xdr);
        nseconds = new uint32_t(xdr);
    }

    }
}
// End of nfstime4.cs
