/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class nfsv4_1_file_layout_ds_addr4 : XdrAble {
    public int [] nflda_stripe_indices;
    public multipath_list4 [] nflda_multipath_ds_list;

    public nfsv4_1_file_layout_ds_addr4() {
    }

    public nfsv4_1_file_layout_ds_addr4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        { int _size = nflda_multipath_ds_list.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { nflda_multipath_ds_list[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        { int _size = xdr.xdrDecodeInt(); nflda_multipath_ds_list = new multipath_list4[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { nflda_multipath_ds_list[_idx] = new multipath_list4(xdr); } }
    }

}
} // End of nfsv4_1_file_layout_ds_addr4.cs
