/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class open_to_lock_owner4 : XdrAble {
    public seqid4 open_seqid;
    public stateid4 open_stateid;
    public seqid4 lock_seqid;
    public lock_owner4 lock_owner;

    public open_to_lock_owner4() {
    }

    public open_to_lock_owner4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        open_stateid.xdrEncode(xdr);
        lock_seqid.xdrEncode(xdr);
        lock_owner.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        open_stateid = new stateid4(xdr);
        lock_seqid = new seqid4(xdr);
        lock_owner = new lock_owner4(xdr);
    }

}
} // End of open_to_lock_owner4.cs
