/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class open_claim_type4
    {

        public const int CLAIM_NULL = 0;
        public const int CLAIM_PREVIOUS = 1;
        public const int CLAIM_DELEGATE_CUR = 2;
        public const int CLAIM_DELEGATE_PREV = 3;
        public const int CLAIM_FH = 4;
        public const int CLAIM_DELEG_CUR_FH = 5;
        public const int CLAIM_DELEG_PREV_FH = 6;

    }
}
 // End of open_claim_type4.cs
