/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class opentype4
    {

        public const int OPEN4_NOCREATE = 0;
        public const int OPEN4_CREATE = 1;

    }
}
 // End of opentype4.cs
