/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class OPEN4args : XdrAble {
    public seqid4 seqid;
    public uint32_t share_access;
    public uint32_t share_deny;
    public open_owner4 owner;
    public openflag4 openhow;
    public open_claim4 claim;


    public OPEN4args() {
    }

    public OPEN4args(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        seqid.xdrEncode(xdr);
        share_access.xdrEncode(xdr);
        share_deny.xdrEncode(xdr);
        owner.xdrEncode(xdr);
        openhow.xdrEncode(xdr);
        claim.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        seqid = new seqid4(xdr);
        share_access = new uint32_t(xdr);
        share_deny = new uint32_t(xdr);
        owner = new open_owner4(xdr);
        openhow = new openflag4(xdr);
        claim = new open_claim4(xdr);
    }

}
} // End of OPEN4args.cs
