/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class open_delegation_type4
    {

        public const int OPEN_DELEGATE_NONE = 0;
        public const int OPEN_DELEGATE_READ = 1;
        public const int OPEN_DELEGATE_WRITE = 2;
        public const int OPEN_DELEGATE_NONE_EXT = 3;

    }
}
 // End of open_delegation_type4.cs
