/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class OPEN_DOWNGRADE4args : XdrAble {
    public stateid4 open_stateid;
    public seqid4 seqid;
    public int share_access;
    public int share_deny;

    public OPEN_DOWNGRADE4args() {
    }

    public OPEN_DOWNGRADE4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        seqid.xdrEncode(xdr);
        xdr.xdrEncodeInt(share_access);
        xdr.xdrEncodeInt(share_deny);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        seqid = new seqid4(xdr);
        share_access = xdr.xdrDecodeInt();
        share_deny = xdr.xdrDecodeInt();
    }

}
} // End of OPEN_DOWNGRADE4args.cs
