/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class OPEN_DOWNGRADE4resok : XdrAble {
    public stateid4 open_stateid;

    public OPEN_DOWNGRADE4resok() {
    }

    public OPEN_DOWNGRADE4resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
    }

    public void xdrDecode(XdrDecodingStream xdr) {
    }

}
} // End of OPEN_DOWNGRADE4resok.cs
