/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class pathname4 : XdrAble {

    public component4 [] value;

    public pathname4() {
    }

    public pathname4(component4 [] value) {
        this.value = value;
    }

    public pathname4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        { int _size = value.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { value[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        { int _size = xdr.xdrDecodeInt(); value = new component4[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { value[_idx] = new component4(xdr); } }
    }

}
} // End of pathname4.cs
