/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class READ4resok : XdrAble {
    public bool eof;
    public byte [] data;

    public READ4resok() {
    }

    public READ4resok(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        xdr.xdrEncodeBoolean(eof);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        eof = xdr.xdrDecodeBoolean();
        data = xdr.xdrDecodeDynamicOpaque();
    }

}
} // End of READ4resok.cs
