/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class READDIR4args : XdrAble {
    public nfs_cookie4 cookie;
    public verifier4 cookieverf;
    public count4 dircount;
    public count4 maxcount;
    public bitmap4 attr_request;


    public READDIR4args() {
    }

    public READDIR4args(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        cookie.xdrEncode(xdr);
        cookieverf.xdrEncode(xdr);
        dircount.xdrEncode(xdr);
        maxcount.xdrEncode(xdr);
        attr_request.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        cookie = new nfs_cookie4(xdr);
        cookieverf = new verifier4(xdr);
        dircount = new count4(xdr);
        maxcount = new count4(xdr);
        attr_request = new bitmap4(xdr);
    }

}
} // End of READDIR4args.cs
