/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class REMOVE4resok : XdrAble {
    public change_info4 cinfo;

    public REMOVE4resok() {
    }

    public REMOVE4resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        cinfo.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        cinfo = new change_info4(xdr);
    }

}
} // End of REMOVE4resok.cs
