/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class RENAME4resok : XdrAble {
    public change_info4 source_cinfo;
    public change_info4 target_cinfo;

    public RENAME4resok() {
    }

    public RENAME4resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        target_cinfo.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        target_cinfo = new change_info4(xdr);
    }

}
} // End of RENAME4resok.cs
