/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class retention_get4 : XdrAble {
    public int rg_duration;
    public nfstime4 [] rg_begin_time;

    public retention_get4() {
    }

    public retention_get4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        { int _size = rg_begin_time.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { rg_begin_time[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        { int _size = xdr.xdrDecodeInt(); rg_begin_time = new nfstime4[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { rg_begin_time[_idx] = new nfstime4(xdr); } }
    }

}
} // End of retention_get4.cs
