/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class seqid4 : XdrAble {

    public uint32_t value;


    public seqid4() {
    }

    public seqid4(uint32_t value) {
        this.value = value;
    }

    public seqid4(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        value.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        value = new uint32_t(xdr);
    }


}
} // End of seqid4.cs
