/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class SEQUENCE4resok : XdrAble {
    public sessionid4 sr_sessionid;
    public sequenceid4 sr_sequenceid;
    public slotid4 sr_slotid;
    public slotid4 sr_highest_slotid;
    public slotid4 sr_target_highest_slotid;
    public uint32_t sr_status_flags;


    public SEQUENCE4resok() {
    }

    public SEQUENCE4resok(XdrDecodingStream xdr)
       {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
 {
        sr_sessionid.xdrEncode(xdr);
        sr_sequenceid.xdrEncode(xdr);
        sr_slotid.xdrEncode(xdr);
        sr_highest_slotid.xdrEncode(xdr);
        sr_target_highest_slotid.xdrEncode(xdr);
        sr_status_flags.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
          {
        sr_sessionid = new sessionid4(xdr);
        sr_sequenceid = new sequenceid4(xdr);
        sr_slotid = new slotid4(xdr);
        sr_highest_slotid = new slotid4(xdr);
        sr_target_highest_slotid = new slotid4(xdr);
        sr_status_flags = new uint32_t(xdr);
    }

}
} // End of SEQUENCE4resok.cs
