/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class SEQUENCE4args : XdrAble {
    public sessionid4 sa_sessionid;
    public sequenceid4 sa_sequenceid;
    public slotid4 sa_slotid;
    public slotid4 sa_highest_slotid;
    public bool sa_cachethis;


    public SEQUENCE4args() {
    }

    public SEQUENCE4args(XdrDecodingStream xdr)
         {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
        {
        sa_sessionid.xdrEncode(xdr);
        sa_sequenceid.xdrEncode(xdr);
        sa_slotid.xdrEncode(xdr);
        sa_highest_slotid.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(sa_cachethis);
    }

    public void xdrDecode(XdrDecodingStream xdr)
        {
        sa_sessionid = new sessionid4(xdr);
        sa_sequenceid = new sequenceid4(xdr);
        sa_slotid = new slotid4(xdr);
        sa_highest_slotid = new slotid4(xdr);
        sa_cachethis = xdr.xdrDecodeBoolean();
    }
}
} // End of SEQUENCE4args.cs
