/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class server_owner4 : XdrAble {
    public uint64_t so_minor_id;
    public byte [] so_major_id;


    public server_owner4() {
    }

    public server_owner4(XdrDecodingStream xdr){
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
  {
        so_minor_id.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(so_major_id);
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        so_minor_id = new uint64_t(xdr);
        so_major_id = xdr.xdrDecodeDynamicOpaque();
    }

}
} // End of server_owner4.cs
