/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class SETCLIENTID4res : XdrAble {
    public int status;
    public SETCLIENTID4resok resok4;
    public clientaddr4 client_using;

    public SETCLIENTID4res() {
    }

    public SETCLIENTID4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(status);
        switch ( status ) {
        case nfsstat4.NFS4_OK:
            resok4.xdrEncode(xdr);
            break;
        case nfsstat4.NFS4ERR_CLID_INUSE:
            client_using.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        status = xdr.xdrDecodeInt();
        switch ( status ) {
        case nfsstat4.NFS4_OK:
            resok4 = new SETCLIENTID4resok(xdr);
            break;
        case nfsstat4.NFS4ERR_CLID_INUSE:
            client_using = new clientaddr4(xdr);
            break;
        default:
            break;
        }
    }

}
} // End of SETCLIENTID4res.cs
