/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class specdata4 : XdrAble {
    public int specdata1;
    public int specdata2;

    public specdata4() {
    }

    public specdata4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(specdata2);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        specdata2 = xdr.xdrDecodeInt();
    }

}
} // End of specdata4.cs
