/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class ssv_seal_cipher_tkn4 : XdrAble {
    public int ssct_ssv_seq;
    public byte [] ssct_iv;
    public byte [] ssct_encr_data;
    public byte [] ssct_hmac;

    public ssv_seal_cipher_tkn4() {
    }

    public ssv_seal_cipher_tkn4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeDynamicOpaque(ssct_iv);
        xdr.xdrEncodeDynamicOpaque(ssct_encr_data);
        xdr.xdrEncodeDynamicOpaque(ssct_hmac);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        ssct_iv = xdr.xdrDecodeDynamicOpaque();
        ssct_encr_data = xdr.xdrDecodeDynamicOpaque();
        ssct_hmac = xdr.xdrDecodeDynamicOpaque();
    }

}
} // End of ssv_seal_cipher_tkn4.cs
