/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class ssv_subkey4
    {

        public const int SSV4_SUBKEY_MIC_I2T = 1;
        public const int SSV4_SUBKEY_MIC_T2I = 2;
        public const int SSV4_SUBKEY_SEAL_I2T = 3;
        public const int SSV4_SUBKEY_SEAL_T2I = 4;

    }
}
 // End of ssv_subkey4.cs
