/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class ssv_mic_tkn4 : XdrAble {
    public int smt_ssv_seq;
    public byte [] smt_hmac;

    public ssv_mic_tkn4() {
    }

    public ssv_mic_tkn4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeDynamicOpaque(smt_hmac);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        smt_hmac = xdr.xdrDecodeDynamicOpaque();
    }

}
} // End of ssv_mic_tkn4.cs
