/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class stable_how4
    {

        public const int UNSTABLE4 = 0;
        public const int DATA_SYNC4 = 1;
        public const int FILE_SYNC4 = 2;

    }
}
 // End of stable_how4.cs
