/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class state_protect4_r : XdrAble {
    public int spr_how;
    public state_protect_ops4 spr_mach_ops;
    public ssv_prot_info4 spr_ssv_info;

    public state_protect4_r() {
    }

    public state_protect4_r(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(spr_how);
        switch ( spr_how ) {
        case state_protect_how4.SP4_NONE:
            break;
        case state_protect_how4.SP4_MACH_CRED:
            spr_mach_ops.xdrEncode(xdr);
            break;
        case state_protect_how4.SP4_SSV:
            spr_ssv_info.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        spr_how = xdr.xdrDecodeInt();
        switch ( spr_how ) {
        case state_protect_how4.SP4_NONE:
            break;
        case state_protect_how4.SP4_MACH_CRED:
            spr_mach_ops = new state_protect_ops4(xdr);
            break;
        case state_protect_how4.SP4_SSV:
            spr_ssv_info = new ssv_prot_info4(xdr);
            break;
        }
    }

}
} // End of state_protect4_r.cs
