/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
/**
 * Enumeration (collection of constants).
 */
public class state_protect_how4 {

    public const int SP4_NONE = 0;
    public const int SP4_MACH_CRED = 1;
    public const int SP4_SSV = 2;

}
} // End of state_protect_how4.cs
