/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class TEST_STATEID4res : XdrAble {
    public int tsr_status;
    public TEST_STATEID4resok tsr_resok4;

    public TEST_STATEID4res() {
    }

    public TEST_STATEID4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(tsr_status);
        switch ( tsr_status ) {
        case nfsstat4.NFS4_OK:
            tsr_resok4.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        tsr_status = xdr.xdrDecodeInt();
        switch ( tsr_status ) {
        case nfsstat4.NFS4_OK:
            tsr_resok4 = new TEST_STATEID4resok(xdr);
            break;
        default:
            break;
        }
    }

}
} // End of TEST_STATEID4res.cs
