/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class WANT_DELEGATION4args : XdrAble {
    public int wda_want;
    public deleg_claim4 wda_claim;

    public WANT_DELEGATION4args() {
    }

    public WANT_DELEGATION4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        wda_claim.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        wda_claim = new deleg_claim4(xdr);
    }

}
} // End of WANT_DELEGATION4args.cs
