/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class WANT_DELEGATION4res : XdrAble {
    public int wdr_status;
    public open_delegation4 wdr_resok4;

    public WANT_DELEGATION4res() {
    }

    public WANT_DELEGATION4res(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(wdr_status);
        switch ( wdr_status ) {
        case nfsstat4.NFS4_OK:
            wdr_resok4.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        wdr_status = xdr.xdrDecodeInt();
        switch ( wdr_status ) {
        case nfsstat4.NFS4_OK:
            wdr_resok4 = new open_delegation4(xdr);
            break;
        default:
            break;
        }
    }

}
} // End of WANT_DELEGATION4res.cs
