/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */
    public class why_no_delegation4
    {

        public const int WND4_NOT_WANTED = 0;
        public const int WND4_CONTENTION = 1;
        public const int WND4_RESOURCE = 2;
        public const int WND4_NOT_SUPP_FTYPE = 3;
        public const int WND4_WRITE_DELEG_NOT_SUPP_FTYPE = 4;
        public const int WND4_NOT_SUPP_UPGRADE = 5;
        public const int WND4_NOT_SUPP_DOWNGRADE = 6;
        public const int WND4_CANCELLED = 7;
        public const int WND4_IS_DIR = 8;

    }
} // End of why_no_delegation4.cs
