/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC{
using org.acplt.oncrpc;

public class WRITE4resok : XdrAble {
    public count4 count;
    public int committed;
    public verifier4 writeverf;


    public WRITE4resok() {
    }

    public WRITE4resok(XdrDecodingStream xdr)
    {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
    {
        count.xdrEncode(xdr);
        xdr.xdrEncodeInt(committed);
        writeverf.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
    {
        count = new count4(xdr);
        committed = xdr.xdrDecodeInt();
        writeverf = new verifier4(xdr);
    }

}
} // End of WRITE4resok.cs
