/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.V2.RPC
{
    public class FileArguments : XdrAble
    {
        private NFSHandle _file;
        private CreateAttributes _attributes;

        public FileArguments()
        { }

        public FileArguments(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            this._file.xdrEncode(xdr);
            this._attributes.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            this._file = new NFSHandle();
            this._file.Version = V2.RPC.NFSv2Protocol.NFS_VERSION;
            this._file.xdrDecode(xdr);
            this._attributes = new CreateAttributes(xdr);
        }

        public NFSHandle File
        {
            get
            { return this._file; }
            set
            { this._file = value; }
        }

        public CreateAttributes Attributes
        {
            get
            { return this._attributes; }
            set
            { this._attributes = value; }
        }
    }
    // End of sattrargs.cs
}