/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.V2.RPC
{
    public class Info : XdrAble
    {
        private int _tsize;
        private int _bsize;
        private int _blocks;
        private int _bfree;
        private int _bavail;

        public Info()
        { }

        public Info(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            xdr.xdrEncodeInt(this._tsize);
            xdr.xdrEncodeInt(this._bsize);
            xdr.xdrEncodeInt(this._blocks);
            xdr.xdrEncodeInt(this._bfree);
            xdr.xdrEncodeInt(this._bavail);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            this._tsize = xdr.xdrDecodeInt();
            this._bsize = xdr.xdrDecodeInt();
            this._blocks = xdr.xdrDecodeInt();
            this._bfree = xdr.xdrDecodeInt();
            this._bavail = xdr.xdrDecodeInt();
        }

        public int TSize
        {
            get
            { return this._tsize; }
        }

        public int BSize
        {
            get
            { return this._bsize; }
        }

        public int Blocks
        {
            get
            { return this._blocks; }
        }

        public int BFree
        {
            get
            { return this._bfree; }
        }

        public int BAvailable
        {
            get
            { return this._bavail; }
        }
    }
    // End of info.cs
}