/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "NFSv2Protocol" ONC/RPC program.
 */
namespace NFSLibrary.Protocols.V2.RPC
{
    public class NFSv2Protocol
    {
        public const int NFS_PROGRAM = 100003;
        public const int NFS_VERSION = 2;

        public const int NFSPROC_NULL = 0;
        public const int NFSPROC_GETATTR = 1;
        public const int NFSPROC_SETATTR = 2;
        public const int NFSPROC_ROOT = 3;
        public const int NFSPROC_LOOKUP = 4;
        public const int NFSPROC_READLINK = 5;
        public const int NFSPROC_READ = 6;
        public const int NFSPROC_WRITECACHE = 7;
        public const int NFSPROC_WRITE = 8;
        public const int NFSPROC_CREATE = 9;
        public const int NFSPROC_REMOVE = 10;
        public const int NFSPROC_RENAME = 11;
        public const int NFSPROC_LINK = 12;
        public const int NFSPROC_SYMLINK = 13;
        public const int NFSPROC_MKDIR = 14;
        public const int NFSPROC_RMDIR = 15;
        public const int NFSPROC_READDIR = 16;
        public const int NFSPROC_STATFS = 17;

        public const int COOKIESIZE = 4;
        public const int MAXPATHLEN = 1024;
        public const int MAXNAMLEN = 255;
        public const int MAXDATA = 8192;
        public const int FHSIZE = 32;
    }
    // End of NFSv2Protocol.cs
}