/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "NFSv2MountProtocol" ONC/RPC program.
 */
namespace NFSLibrary.Protocols.V2.RPC.Mount
{
    public class NFSv2MountProtocol
    {
        public const int MOUNTPROG = 100005;
        public const int MOUNTVERS = 1;

        public const int MOUNTPROC_NULL = 0;
        public const int MOUNTPROC_MNT = 1;
        public const int MOUNTPROC_DUMP = 2;
        public const int MOUNTPROC_UMNT = 3;
        public const int MOUNTPROC_UMNTALL = 4;
        public const int MOUNTPROC_EXPORT = 5;

        public const int MNTPATHLEN = 1024;
        public const int MNTNAMLEN = 255;
        public const int FHSIZE = 32;
    }
    // End of NFSv2MountProtocol.cs
}