/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

public class CB_GETATTR4resok : XdrAble {
    public fattr4 obj_attributes;

    public CB_GETATTR4resok() {
    }

    public CB_GETATTR4resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
    }

    public void xdrDecode(XdrDecodingStream xdr) {
    }

}
} // End of CB_GETATTR4resok.cs
