/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

public class CB_NOTIFY4args : XdrAble {
    public stateid4 cna_stateid;
    public nfs_fh4 cna_fh;
    public notify4 [] cna_changes;

    public CB_NOTIFY4args() {
    }

    public CB_NOTIFY4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        cna_fh.xdrEncode(xdr);
        { int _size = cna_changes.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { cna_changes[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        cna_fh = new nfs_fh4(xdr);
        { int _size = xdr.xdrDecodeInt(); cna_changes = new notify4[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { cna_changes[_idx] = new notify4(xdr); } }
    }

}
} // End of CB_NOTIFY4args.cs
