/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

public class CB_PUSH_DELEG4args : XdrAble {
    public nfs_fh4 cpda_fh;
    public open_delegation4 cpda_delegation;

    public CB_PUSH_DELEG4args() {
    }

    public CB_PUSH_DELEG4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        cpda_delegation.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        cpda_delegation = new open_delegation4(xdr);
    }

}
} // End of CB_PUSH_DELEG4args.cs
