/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

public class CB_RECALL4args : XdrAble {
    public stateid4 stateid;
    public bool truncate;
    public nfs_fh4 fh;

    public CB_RECALL4args() {
    }

    public CB_RECALL4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeBoolean(truncate);
        fh.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        truncate = xdr.xdrDecodeBoolean();
        fh = new nfs_fh4(xdr);
    }

}
} // End of CB_RECALL4args.cs
