/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

public class CB_RECALL_ANY4args : XdrAble {
    public int craa_objects_to_keep;
    public bitmap4 craa_type_mask;

    public CB_RECALL_ANY4args() {
    }

    public CB_RECALL_ANY4args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        craa_type_mask.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        craa_type_mask = new bitmap4(xdr);
    }

}
} // End of CB_RECALL_ANY4args.cs
