/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
/**
 * Enumeration (collection of constants).
 */
public class nfs_cb_opnum4 {

    public const int OP_CB_GETATTR = 3;
    public const int OP_CB_RECALL = 4;
    public const int OP_CB_LAYOUTRECALL = 5;
    public const int OP_CB_NOTIFY = 6;
    public const int OP_CB_PUSH_DELEG = 7;
    public const int OP_CB_RECALL_ANY = 8;
    public const int OP_CB_RECALLABLE_OBJ_AVAIL = 9;
    public const int OP_CB_RECALL_SLOT = 10;
    public const int OP_CB_SEQUENCE = 11;
    public const int OP_CB_WANTS_CANCELLED = 12;
    public const int OP_CB_NOTIFY_LOCK = 13;
    public const int OP_CB_NOTIFY_DEVICEID = 14;
    public const int OP_CB_ILLEGAL = 10044;

}
} // End of nfs_cb_opnum4.cs
