/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

using System.Net;

using org.acplt.oncrpc.server;

/**
 */
public abstract class NFSv4_callbackServerStub : OncRpcServerStub, OncRpcDispatchable {

    public NFSv4_callbackServerStub() : this(0) {
    }

    public NFSv4_callbackServerStub(int port) : this(null, port) {
    }

    public NFSv4_callbackServerStub(IPAddress bindAddr, int port)
           {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(NFSv4_callback.NFS4_CALLBACK, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
            {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 0: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                CB_NULL_1();
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 1: {
                CB_COMPOUND4args args_ = new CB_COMPOUND4args();
                call.retrieveCall(args_);
                CB_COMPOUND4res result_ = CB_COMPOUND_1(args_);
                call.reply(result_);
                break;
            }
            default:
                call.failProcedureUnavailable();
                break;
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract void CB_NULL_1();

    public abstract CB_COMPOUND4res CB_COMPOUND_1(CB_COMPOUND4args arg1);

}
} // End of NFSv4_callbackServerStub.cs
