/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
/**
 * A collection of constants used by the "NFSv4_callback" ONC/RPC program.
 */
public class NFSv4_callback {
    public const int NFS4_CALLBACK = 0x40000000;
    public const int RCA4_TYPE_MASK_FILE_LAYOUT = 3;
    public const int RCA4_TYPE_MASK_OTHER_LAYOUT_MIN = 12;
    public const int RCA4_TYPE_MASK_OTHER_LAYOUT_MAX = 15;
    public const int CB_NULL_1 = 0;
    public const int RCA4_TYPE_MASK_RDATA_DLG = 0;
    public const int RCA4_TYPE_MASK_OBJ_LAYOUT_MIN = 8;
    public const int RCA4_TYPE_MASK_BLK_LAYOUT = 4;
    public const int RCA4_TYPE_MASK_WDATA_DLG = 1;
    public const int NFS_CB = 1;
    public const int RCA4_TYPE_MASK_OBJ_LAYOUT_MAX = 9;
    public const int RCA4_TYPE_MASK_DIR_DLG = 2;
    public const int CB_COMPOUND_1 = 1;
}
} // End of NFSv4_callback.cs
