/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

public class notify_deviceid_delete4 : XdrAble {
    public layouttype4 ndd_layouttype;
    public deviceid4 ndd_deviceid;

    public notify_deviceid_delete4() {
    }

    public notify_deviceid_delete4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        ndd_deviceid.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        ndd_deviceid = new deviceid4(xdr);
    }

}
} // End of notify_deviceid_delete4.cs
