/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
/**
 * Enumeration (collection of constants).
 */
public class notify_deviceid_type4 {

    public static readonly int NOTIFY_DEVICEID4_CHANGE = 1;
    public static readonly int NOTIFY_DEVICEID4_DELETE = 2;

}
} // End of notify_deviceid_type4.cs
