/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
using org.acplt.oncrpc;

public class notify_entry4 : XdrAble {
    public component4 ne_file;
    public fattr4 ne_attrs;

    public notify_entry4() {
    }

    public notify_entry4(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        ne_attrs.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        ne_attrs = new fattr4(xdr);
    }

}
} // End of notify_entry4.cs
