/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
namespace NFSLibrary.Protocols.V4.RPC.Callback{
/**
 * Enumeration (collection of constants).
 */
public class notify_type4 {

    public static readonly int NOTIFY4_CHANGE_CHILD_ATTRS = 0;
    public static readonly int NOTIFY4_CHANGE_DIR_ATTRS = 1;
    public static readonly int NOTIFY4_REMOVE_ENTRY = 2;
    public static readonly int NOTIFY4_ADD_ENTRY = 3;
    public static readonly int NOTIFY4_RENAME_ENTRY = 4;
    public static readonly int NOTIFY4_CHANGE_COOKIE_VERIFIER = 5;

}
} // End of notify_type4.cs
