/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class GetAttributeAccessOK : XdrAble
    {
        private FileAttributes _obj_attributes;

        public GetAttributeAccessOK()
        { }

        public GetAttributeAccessOK(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        { this._obj_attributes.xdrEncode(xdr); }

        public void xdrDecode(XdrDecodingStream xdr)
        { this._obj_attributes = new FileAttributes(xdr); }

        public FileAttributes Attributes
        {
            get
            { return this._obj_attributes; }
        }
    }
    // End of GETATTR3res.cs
}