/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class LinkArguments : XdrAble
    {
        private NFSHandle _file;
        private ItemOperationArguments _link;

        public LinkArguments()
        { }

        public LinkArguments(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            this._file.xdrEncode(xdr);
            this._link.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            this._file = new NFSHandle();
            this._file.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            this._file.xdrDecode(xdr);
            this._link = new ItemOperationArguments(xdr);
        }

        public NFSHandle Handle
        {
            get
            { return this._file; }
            set
            { this._file = value; }
        }

        public ItemOperationArguments Link
        {
            get
            { return this._link; }
            set
            { this._link = value; }
        }
    }
    // End of LINK3args.cs
}