/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class NFSCookie : XdrAble
    {
        private long _value;

        public NFSCookie()
        { }

        public NFSCookie(long value)
        { this._value = value; }

        public NFSCookie(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        { xdr.xdrEncodeLong(this._value); }

        public void xdrDecode(XdrDecodingStream xdr)
        { this._value = xdr.xdrDecodeLong(); }

        public long Value
        {
            get
            { return this._value; }
        }
    }
    // End of cookie3.cs
}

