/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class RenameAccessOK : XdrAble
    {
        private WritingData _fromdir_wcc;
        private WritingData _todir_wcc;

        public RenameAccessOK()
        { }

        public RenameAccessOK(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            this._fromdir_wcc.xdrEncode(xdr);
            this._todir_wcc.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            this._fromdir_wcc = new WritingData(xdr);
            this._todir_wcc = new WritingData(xdr);
        }

        public WritingData From
        {
            get
            { return this._fromdir_wcc; }
        }

        public WritingData To
        {
            get
            { return this._todir_wcc; }
        }
    }

    public class RenameAccessFAIL : XdrAble
    {
        private WritingData _fromdir_wcc;
        private WritingData _todir_wcc;

        public RenameAccessFAIL()
        { }

        public RenameAccessFAIL(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            this._fromdir_wcc.xdrEncode(xdr);
            this._todir_wcc.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            this._fromdir_wcc = new WritingData(xdr);
            this._todir_wcc = new WritingData(xdr);
        }

        public WritingData From
        {
            get
            { return this._fromdir_wcc; }
        }

        public WritingData To
        {
            get
            { return this._todir_wcc; }
        }
    }
    // End of WRITE3res.cs
}