/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class SpecInformation : XdrAble
    {
        private int _specdata1;
        private int _specdata2;

        public SpecInformation()
        { }

        public SpecInformation(XdrDecodingStream xdr)
        { xdrDecode(xdr); }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            xdr.xdrEncodeInt(this._specdata1);
            xdr.xdrEncodeInt(this._specdata2);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            this._specdata1 = xdr.xdrDecodeInt();
            this._specdata2 = xdr.xdrDecodeInt();
        }

        public int SpecData1
        {
            get
            { return this._specdata1; }
        }

        public int SpecData2
        {
            get
            { return this._specdata2; }
        }
    }
    // End of specdata3.cs
}